### ISSUE TITLE
Request: Option to disable paging

### ISSUE THREAD

**Issue by AndydeCleyre** [walles/riff#24]
Sometimes I want to ensure the pager is not used, and can achieve that result by setting `PAGER=cat`, but I would prefer to use something like `--no-pager`.

Thanks for this project!

**Comment by walles** [comment]
Sounds like a reasonable request.

I can't tell you *when* I'll get to it, but I will.

Unless somebody beats me to it with a PR.

**Comment by walles** [comment]
Done in 2.16.

**Comment by AndydeCleyre** [comment]
Thank you very much!
