### ISSUE TITLE
Test failure when specifying a target triple

### ISSUE THREAD

**Issue by 0x5c** [walles/riff#25]
`tests::test_testdata_examples` fails since the binary path gains a new path component when a target is specified.

`target/release/deps/riff-[hash]` becomes  
`target/[triple]/release/deps/riff-[hash]`

**Comment by walles** [comment]
Can you provide the exact command line you used to get this failure?

**Comment by 0x5c** [comment]
Anything that specifies the target triple when doing `cargo test`, in my case `--target [a target triple]`. This happens regardless of the triple being the host triple or not.

My host being `x86_64-unknown-linux-gnu`, explicitly specifying that triple or `x86_64-unknown-linux-musl` causes the binary's path to have the target added, and that specific test to fail.

**Comment by walles** [comment]
Thanks for reporting @0x5c!

I used `cargo test --target x86_64-apple-darwin` to repro.
