### ISSUE TITLE
unable to compare output of commands with bash/zsh redirection

### ISSUE THREAD

**Issue by classabbyamp** [walles/riff#29]
in bash and zsh (and maybe other shells), the `<()` operator redirects a command's output as a file descriptor using a FIFO. This can be used with gnu diff to compare the outputs of commands (as shown below), but it doesn't work with riff. Would it be possible to add support for this?

```bash
$ diff <(cmd1) <(cmd2)
# works
$ riff <(cmd1) <(cmd2)
Can only compare file to file or directory to directory, not like this:
  Not file not dir: /proc/self/fd/11
  Not file not dir: /proc/self/fd/12
```

**Comment by walles** [comment]
Released with 2.16.3 about twelve hours ago.
