### ISSUE TITLE
Installation via cargo

### ISSUE THREAD

**Issue by roland-5** [walles/riff#31]
Would be possible for you, to put `riff` to `crates.io` and thank to this install `riff` with `cargo install riff`?

**Comment by walles** [comment]
Done: <https://crates.io/crates/riffdiff>

If you try `cargo install riffdiff`, please report back here how it worked for you @roland-rollo!

**Comment by roland-5** [comment]
Wow, that was quick! Worked like heaven. I searched for something like `riff` for sooo looong. Excellent job, mate! Thank you.

**Comment by walles** [comment]
Thanks for verifying @roland-rollo!

**Comment by walles** [comment]
Heads up that I just fixed the `cargo install` binary name.

The binary is now called `riff` and nothing else, which should always have been the case.
