### ISSUE TITLE
Request of windows binaries

### ISSUE THREAD

**Issue by lazybadger** [walles/riff#36]
Because

> If no binary exists for your platform, please report it

and **not everybody** (from potential users) can build from Rust-sources by hand

**Comment by walles** [comment]
@lazybadger can you try this binary and see if it works for you?

[riff.exe.gz](https://github.com/walles/riff/files/10179841/riff.exe.gz)

I built it using [these instructions](https://gist.github.com/Mefistophell/9787e1b6d2d9441c16d2ac79d6a505e6), but I have no way of verifying whether it works.

**Comment by walles** [comment]
Also, note to self, if this actually works I need to add crash testing CI for Windows.

**Comment by lazybadger** [comment]
> @lazybadger can you try this binary and see if it works for you?
Tested:

Works without (visible detectable) errors to the minimum required extent (piping), crash-dumped on case `riff file1 file2` (stderr attached here), which is low-priority issue from my POV

[crash.txt](https://github.com/walles/riff/files/10185444/crash.txt)

**Comment by walles** [comment]
Can you try this one and see if it still crashes on `riff file1 file2`?

[riff.exe.gz](https://github.com/walles/riff/files/10188299/riff.exe.gz)

If `riff` randomly crashes I'll get other tickets about that so I'd prefer if it doesn't.

Thanks for testing!

**Comment by lazybadger** [comment]
> Can you try this one and see if it still crashes on `riff file1 file2`?

No crashes (PowerShell + CMD), but no diff with

```
ERROR: Spawning diff failed:
  "diff" "-ur" "--show-c-function" "--new-file" "old.py" "new.py"
  program not found
```
(yes, I haven't separate diff)

**Comment by walles** [comment]
Done: <https://github.com/walles/riff/releases/tag/2.22.2>
