### ISSUE TITLE
Ability to pass a diff/patch file as single argument 

### ISSUE THREAD

**Issue by 0x5c** [walles/riff#44]
I often find myself wanting to have riff highlighting on a patch file. As of the current riff version, the only way to do that is to pipe the patch's content to riff. I however always fail to remember that and instead attempt to pass the patch's path as an argument.

It would be nice if riff would treat the case of only one non-flag argument as a signal to apply diff highlighting to the file's content, as if it had been passed as stdin.

Alternatively, this could be done with a flag like `--(f)ile`. This would still be more intuitive than `cat <patch> | riff`.

```
riff <file1> <file2>
# the diff of file1 and file2, highlighted; existing functionnality
riff <patchfile>
# the contents of patchfile, highlighted
```

**Comment by walles** [comment]
How about this? This is what I use.

```sh
riff < hello.diff
```

**Comment by 0x5c** [comment]
> How about this? This is what I use.
> 
> ```shell
> riff < hello.diff
> ```

Way less "natural" than even piping from `cat`, at least for me. It's a "pattern" I encounter/use very rarely, contrary to `cat <file> | cmd`, `cmd <file>`, and `cmd -f <file>`

**Comment by walles** [comment]
I think having an option for this would be fine.

Maybe `--file` or `-f` as you hinted at.

I'd slightly prefer having the `--file` form only, to lower the risk of colliding with any plain `diff` options. But neither macOS `diff` nor GNU `diff` has any short `-f` option so I guess just `-f` should be fine as well.

Wanna make a PR?

**Comment by 0x5c** [comment]
> Wanna make a PR?

sure I'll have a look

**Comment by 0x5c** [comment]
So I finally had the time to have a look, but with the way the custom argument parser is done it's going to be painful to add a flag that takes an option.

**Comment by 0x5c** [comment]
In this dive in the code, I found a funny bug
![image](https://github.com/walles/riff/assets/5877043/c018e483-02ae-4aa5-b2e4-8a28e0458ca1)

`consume()` is so over-eager that it deletes the second file from argv.

Additionally, it would normally be possible to end option/flag parsing with `--` like in the `touch` calls, but riff does not support that
![image](https://github.com/walles/riff/assets/5877043/13f76de0-deb0-42e8-a4e8-741c155132f1)


I would recommend switching to an argument parsing crate like `clap`, both to ease extensibility, to avoid argument parsing edge-cases like these, to provide proper CLI validation, and to follow [argument parsing conventions and best practices](https://clig.dev/#arguments-and-flags) like `--`. The structure of the rest of the code would make that an easy switch. I also offer to make a PR for that.

**Comment by walles** [comment]
I started looking into that here:
https://github.com/walles/riff/commits/johan/clap

It mostly works, but Clap supports only one `Usage` description which I find unfortunate. Not sure what to do with that...

**Comment by 0x5c** [comment]
> It mostly works, but Clap supports only one `Usage` description which I find unfortunate. Not sure what to do with that...

Ah yeah clap's default is not the best. You can override the usage line(s) with [`override_usage`](https://docs.rs/clap/latest/clap/struct.Command.html#method.override_usage) and it supports multiple lines

To use it with the derive, you just add `override_usage = USAGE` here
https://github.com/walles/riff/blob/d1c5c71791d8acf009f20b704173d07a4d0b58fd/src/main.rs#L59

**Comment by 0x5c** [comment]
Successfully added it back

![image](https://github.com/walles/riff/assets/5877043/ee2bfc8a-b573-4c0a-b238-2a949b999fa2)



```diff
diff --git a/src/main.rs b/src/main.rs
index 97c818e..6964892 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -29,6 +29,10 @@ mod refiner;
 mod token_collector;
 mod tokenizer;
 
+const USAGE: &str = "diff ... | riff\n       \
+    riff [-b] [--no-pager] <file1> <file2>\n       \
+    riff [-b] [--no-pager] <directory1> <directory2>";
+
 const HELP_TEXT_FOOTER: &str = r#"Installing riff in the $PATH:
     sudo cp riff /usr/local/bin
 
@@ -56,7 +60,7 @@ const PAGER_FORKBOMB_STOP: &str = "_RIFF_IGNORE_PAGER";
 const GIT_VERSION: &str = git_version!(cargo_prefix = "");
 
 #[derive(Parser)]
-#[command(version = GIT_VERSION, name = "riff", about = "Colors diff output, highlighting the changed parts of every line.", after_help = HELP_TEXT_FOOTER)]
+#[command(version = GIT_VERSION, name = "riff", about = "Colors diff output, highlighting the changed parts of every line.", after_help = HELP_TEXT_FOOTER, override_usage = USAGE)]
 struct Options {
     /// First file to compare
     #[arg(requires("file2"))]
```

`file1` and `file2` could be `Option<PathBuf>` to automatically get a valid path, and the check for the paths being file-file or dir-dir could be done earlier since the paths would already be paths from the get-go.

**Comment by walles** [comment]
Branch merged, thanks for the help!

If you see something that can be adjusted do let me know.

*Now* it should be rather straight forward to add that new option!

**Comment by 0x5c** [comment]
> If you see something that can be adjusted do let me know.

The lack of the seven spaces on the usage lines gives an odd rendering to the usage lines, since they normally start on the same line as `Usage:` in most cli tools, but that's just styling.

**Comment by walles** [comment]
> The lack of the seven spaces on the usage lines gives an odd rendering to the usage lines, since they normally start on the same line as `Usage:` in most cli tools, but that's just styling.

Arguments and Options are indented by two, so I'll stick to that for Usage as well.

As you say, this is a matter of taste...
