### ISSUE TITLE
Misaligned timestamps

### ISSUE THREAD

**Issue by sergeevabc** [walles/riff#58]
Windows 7 x64 user here. I was looking for a speedy alternative to `diff` and came across `riff` (2.28.0). It is indeed way faster than `busybox diff file1 file2` on my end. However, the output contains poorly aligned timestamps. Please, a) align timestamps and b) implement an option to omit them altogether (for example, to share diff via pastebins without exposing that kind of metadata).

``` console
$ riff original.hex patched.hex
--- original.hex        Thu Jan 25 23:37:19 2024
+++ patched.hex Thu Jan 25 23:38:40 2024
@@ -419964,7 +419964,7 @@
...

$ busybox diff original.hex patched.hex | riff
--- original.hex
+++ patched.hex
@@ -419964,7 +419964,7 @@
```

_Originally posted by @sergeevabc in https://github.com/walles/riff/issues/47#issuecomment-1911136451_

**Comment by walles** [comment]
Let's start with aligning the timestamps.

**Comment by sergeevabc** [comment]
@walles, I confirm that timestamps are now aligned on my end. Thank you.
