### ISSUE TITLE
Output is colored even when redirecting it into a pipe

### ISSUE THREAD

**Issue by alvaroaleman** [walles/riff#59]
Basically title, when doing `riff a b|some-command` I'd expect there to not be any color codes but there are.

**Comment by walles** [comment]
In what situation would you want to pipe `riff`'s output to something else?

On one hand, what you suggest is done by things like `ls`, but on the other hand, a large part of the point of `riff` is to add color, so not adding color could be weird.

**Comment by alvaroaleman** [comment]
> In what situation would you want to pipe riff's output to something else?

I am piping it into `pbcopy` to get it into the clipboard, because the format even without colors is easier to read than what `diff` outputs

**Comment by walles** [comment]
Sounds reasonable.

Where do you intend to paste it? Some markdown document, a web page, mail, ... ?

**Comment by alvaroaleman** [comment]
> Where do you intend to paste it? Some markdown document, a web page, mail, ... ?

In this case it was a GitHub PR description, but could be anything (slack message, mail)

**Comment by walles** [comment]
This makes sense.

Additionally I think there should be a command line flag `--color=yes` or `--color=no` to force the behavior.

**Comment by alvaroaleman** [comment]
Yep, agree. I actually tried to find that as a workaround but couldn't, so
ended up using some sed to strip the color codes. Also, it doesn't seem
like the NO_COLOR env var is respected.

**Comment by walles** [comment]
# Workaround

```
diff -ur a b
```

---

This is what `riff` does internally anyway, and then it highlights the output.

https://github.com/walles/riff/blob/861590fbba98efc895110c8e409ee7e4e0304138/src/main.rs#L329-L342

**Comment by walles** [comment]
Released: <https://github.com/walles/riff/releases/tag/2.32.0>

**Comment by alvaroaleman** [comment]
Thank you!
