### ISSUE TITLE
setting riff for log pager removes log colours

### ISSUE THREAD

**Issue by classabbyamp** [walles/riff#62]
`git log --oneline --decorate --graph` normally shows colours:
![image](https://github.com/walles/riff/assets/5366828/9a7ca3a2-cddd-408e-a8ca-544d1b0573b2)

but if `git config --global pager.log riff` is set, the colours disappear:
![image](https://github.com/walles/riff/assets/5366828/3f30b3a9-a52f-4941-83dd-921d3d5bc7e9)

**Comment by walles** [comment]
Noted, and I agree this is a problem that should be fixed.

A workaround (not a fix) in the mean time, would be to not use `riff` for logs. That would make `git log -p` not be highlighted properly, which makes this a workaround and not a fix:
```
git config --unset --global pager.log
```

Having thought about this a bit, I think it should be pretty straight forward for `riff` to either:
* Add color to some incoming line, just like before
* If `riff` doesn't add color to some line, pass it through unchanged, retaining any existing formatting
