### ISSUE TITLE
Option to mark whole words

### ISSUE THREAD

**Issue by thoni56** [walles/riff#7]
Currently  a diff between

    uintptr_t | CgreenValue

comes out as

<pre>
    <b>uintpt</b><i>r</i><b>_t</b> | <b>Cg</b><i>r</i><b>eenValue</b>
</pre>

That doesn't show very well since it's not possible to color backgrounds here, but all except the 'r' is marked as different. It would be nice with an option to not be so detailed but instead regard whole words instead. For some definition of 'word'.

It is usually what you are interested in and much easier to read.

Love `riff` anyway!

**Comment by walles** [comment]
Done in 2.0: <https://github.com/walles/riff/releases>

Sorry about the lead time, I failed at Github :(.
