### ISSUE TITLE
Leak of control characters

### ISSUE THREAD

**Issue by xeago** [walles/riff#9]
Hiya!

While using riff-2.0/riff-2.2 as a pager, I've encountered a diff that causes it to leak control characters. Piping the raw diff into `riff` reproduces with the same results. Using [Kitty](https://sw.kovidgoyal.net/kitty/) as terminal emulator. Annoyingly this does not occur on Apple Terminal.

---
Raw diff: `git diff | cat`
```
diff --git a/app.yaml b/app.yaml
index 2da370d..f7f39fc 100644
--- a/app.yaml
+++ b/app.yaml
@@ -11,10 +11,8 @@ handlers:
 -   url: /api/.*
     script: auto
 -   url: /(.*)
-    static_files: ui/dist/\1
-    upload: ui/dist/(.*)
-error_handlers:
--   file: ui/dist/default_error.html
+    static_files: ui/build/\1
+    upload: ui/build/(.*)
 env_variables:
     PGUSER: postgres
     CLOUD_SQL_CONNECTION_NAME: /cloudsql/animated-sniffle:europe-west1:pg-animated-sniffle
```

Diff as textual render: `git diff`
```
diff --git a/app.yaml b/app.yaml
index 2da370d..f7f39fc 100644
--- a/app.yaml
+++ b/app.yaml
@@ -11,10 +11,8 @@ handlers:
 -   url: /api/.*
     script: auto
 -   url: /(.*)
-    static_files: ui/dist/\1
-    upload: ui/dist/(.*)<E2><8F><8E>
-error_handlers:<E2><8F><8E>
--   file: ui/dist/default_error.html
+    static_files: ui/build/\1
+    upload: ui/build/(.*)
 env_variables:
     PGUSER: postgres
     CLOUD_SQL_CONNECTION_NAME: /cloudsql/animated-sniffle:europe-west1:pg-animated-sniffle
```

Diff as graphical render:
<img width="355" alt="image" src="https://user-images.githubusercontent.com/770778/100740534-c9653780-33d0-11eb-9bf4-d283f5d85d85.png">
---

**Comment by xeago** [comment]
Piping the result of `riff` into `cat` _removes/hides_ the control characters…

**Comment by walles** [comment]
Hey there @xeago!

The character that's being leaked is this one:

<https://www.fileformat.info/info/unicode/char/23ce/index.htm>

If you look at that page you can see `<E2><8F><8E>` is the UTF8 sequence for ⏎.

Which is my way of making added / removed newlines visible.

Unclear why that renders badly for you, here's what I get:
<img width="270" alt="utf-8-rendered-newline-symbol" src="https://user-images.githubusercontent.com/158201/100780797-77410800-340a-11eb-87fa-e7d9623b7496.png">

What if you copy / paste `räksmörgås` into your terminal, does that render properly for you?

Excellent that you could provide a repro case!

**Comment by walles** [comment]
What if you do this?

```
~ $ locale
LANG="sv_SE.UTF-8"
LC_COLLATE="sv_SE.UTF-8"
LC_CTYPE="sv_SE.UTF-8"
LC_MESSAGES="sv_SE.UTF-8"
LC_MONETARY="sv_SE.UTF-8"
LC_NUMERIC="sv_SE.UTF-8"
LC_TIME="sv_SE.UTF-8"
LC_ALL=
~ $
```

**Comment by walles** [comment]
I just tried this with Kitty as well and it worked fine, my best guess is that this is related to `locale` / Kitty UTF-8 settings.

**Comment by xeago** [comment]
That is indeed the case; all except `LANG` were set to `C`. Interestingly enough, while I could `echo räksmörgås` just fine, `echo räksmörgås | pbcopy; pbpaste` would fail.

✨
